# Generated by Django 2.2.6 on 2021-02-27 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Прозвище')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('description', models.TextField()),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Возраст')),
                ('date_of_receipt', models.DateTimeField(auto_now=True, verbose_name='Дата прихода')),
                ('image', models.ImageField(blank=True, upload_to='photo')),
                ('type_of_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_home.TypeOfAnimal')),
            ],
        ),
    ]
